### ISSUE TITLE
parser Prettier option forces filetype and results in false positives

### ISSUE THREAD

**Issue by grissius** [AckeeCZ/prettier-config-ackee#1]
# [parser](https://prettier.io/docs/en/options.html#parser)

### What is the current value?

typescript

### Why have you decided to change it?

It forces to validate all files as TS files. When using `pretty-quick --staged` and JSON is staged, false positive is reported. For further details, see https://github.com/azz/pretty-quick/issues/23

### What benefit will it bring to the rest of the team?

Correct behavior

### New value:

Not sure, but ommiting the value might work, prettier will decide what file it is.

Do you agree?

- :thumbsup: yup
- :man-shrugging: dunno
- :thumbsdown: nope

**Comment by vlasy** [comment]
I think that omitting should work, as by default, Prettier detects parser automatically by file extension.

👍
